/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientRequestsRouteImport } from './routes/client-requests'
import { Route as ApiJiraWebhookRouteImport } from './routes/api.jira-webhook'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRequestsRoute = ClientRequestsRouteImport.update({
  id: '/client-requests',
  path: '/client-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJiraWebhookRoute = ApiJiraWebhookRouteImport.update({
  id: '/api/jira-webhook',
  path: '/api/jira-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client-requests': typeof ClientRequestsRoute
  '/api/jira-webhook': typeof ApiJiraWebhookRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/client-requests': typeof ClientRequestsRoute
  '/api/jira-webhook': typeof ApiJiraWebhookRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/client-requests': typeof ClientRequestsRoute
  '/api/jira-webhook': typeof ApiJiraWebhookRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/client-requests' | '/api/jira-webhook' | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/client-requests' | '/api/jira-webhook' | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/client-requests'
    | '/api/jira-webhook'
    | '/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientRequestsRoute: typeof ClientRequestsRoute
  ApiJiraWebhookRoute: typeof ApiJiraWebhookRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-requests': {
      id: '/client-requests'
      path: '/client-requests'
      fullPath: '/client-requests'
      preLoaderRoute: typeof ClientRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jira-webhook': {
      id: '/api/jira-webhook'
      path: '/api/jira-webhook'
      fullPath: '/api/jira-webhook'
      preLoaderRoute: typeof ApiJiraWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientRequestsRoute: ClientRequestsRoute,
  ApiJiraWebhookRoute: ApiJiraWebhookRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
