/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NextSprintRouteImport } from './routes/next-sprint'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as ApiClaritySplatRouteImport } from './routes/api.clarity.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NextSprintRoute = NextSprintRouteImport.update({
  id: '/next-sprint',
  path: '/next-sprint',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClaritySplatRoute = ApiClaritySplatRouteImport.update({
  id: '/api/clarity/$',
  path: '/api/clarity/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/next-sprint': typeof NextSprintRoute
  '/people': typeof PeopleRoute
  '/planning': typeof PlanningRoute
  '/projects': typeof ProjectsRoute
  '/trends': typeof TrendsRoute
  '/api/clarity/$': typeof ApiClaritySplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/next-sprint': typeof NextSprintRoute
  '/people': typeof PeopleRoute
  '/planning': typeof PlanningRoute
  '/projects': typeof ProjectsRoute
  '/trends': typeof TrendsRoute
  '/api/clarity/$': typeof ApiClaritySplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/next-sprint': typeof NextSprintRoute
  '/people': typeof PeopleRoute
  '/planning': typeof PlanningRoute
  '/projects': typeof ProjectsRoute
  '/trends': typeof TrendsRoute
  '/api/clarity/$': typeof ApiClaritySplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/next-sprint'
    | '/people'
    | '/planning'
    | '/projects'
    | '/trends'
    | '/api/clarity/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/next-sprint'
    | '/people'
    | '/planning'
    | '/projects'
    | '/trends'
    | '/api/clarity/$'
  id:
    | '__root__'
    | '/'
    | '/next-sprint'
    | '/people'
    | '/planning'
    | '/projects'
    | '/trends'
    | '/api/clarity/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NextSprintRoute: typeof NextSprintRoute
  PeopleRoute: typeof PeopleRoute
  PlanningRoute: typeof PlanningRoute
  ProjectsRoute: typeof ProjectsRoute
  TrendsRoute: typeof TrendsRoute
  ApiClaritySplatRoute: typeof ApiClaritySplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/next-sprint': {
      id: '/next-sprint'
      path: '/next-sprint'
      fullPath: '/next-sprint'
      preLoaderRoute: typeof NextSprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clarity/$': {
      id: '/api/clarity/$'
      path: '/api/clarity/$'
      fullPath: '/api/clarity/$'
      preLoaderRoute: typeof ApiClaritySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NextSprintRoute: NextSprintRoute,
  PeopleRoute: PeopleRoute,
  PlanningRoute: PlanningRoute,
  ProjectsRoute: ProjectsRoute,
  TrendsRoute: TrendsRoute,
  ApiClaritySplatRoute: ApiClaritySplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
