/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamHealthRouteImport } from './routes/team-health'
import { Route as ResourcePlanningRouteImport } from './routes/resource-planning'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as IndexRouteImport } from './routes/index'

const TeamHealthRoute = TeamHealthRouteImport.update({
  id: '/team-health',
  path: '/team-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcePlanningRoute = ResourcePlanningRouteImport.update({
  id: '/resource-planning',
  path: '/resource-planning',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/people': typeof PeopleRoute
  '/projects': typeof ProjectsRoute
  '/resource-planning': typeof ResourcePlanningRoute
  '/team-health': typeof TeamHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/people': typeof PeopleRoute
  '/projects': typeof ProjectsRoute
  '/resource-planning': typeof ResourcePlanningRoute
  '/team-health': typeof TeamHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/people': typeof PeopleRoute
  '/projects': typeof ProjectsRoute
  '/resource-planning': typeof ResourcePlanningRoute
  '/team-health': typeof TeamHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/people'
    | '/projects'
    | '/resource-planning'
    | '/team-health'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/people' | '/projects' | '/resource-planning' | '/team-health'
  id:
    | '__root__'
    | '/'
    | '/people'
    | '/projects'
    | '/resource-planning'
    | '/team-health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PeopleRoute: typeof PeopleRoute
  ProjectsRoute: typeof ProjectsRoute
  ResourcePlanningRoute: typeof ResourcePlanningRoute
  TeamHealthRoute: typeof TeamHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team-health': {
      id: '/team-health'
      path: '/team-health'
      fullPath: '/team-health'
      preLoaderRoute: typeof TeamHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resource-planning': {
      id: '/resource-planning'
      path: '/resource-planning'
      fullPath: '/resource-planning'
      preLoaderRoute: typeof ResourcePlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PeopleRoute: PeopleRoute,
  ProjectsRoute: ProjectsRoute,
  ResourcePlanningRoute: ResourcePlanningRoute,
  TeamHealthRoute: TeamHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
